# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

    - task: NeuVectorScan@3
      inputs:
        scanType: 'standalone'
        nvContainerRegistry: 'docker hub lsong'
        nvRepository: 'songlongtj/scanner'
        nvTag: '5.0'
        containerRegistry: 'docker hub lsong'
        repository: 'songlongtj/alpine'
        tag: '3.10'